"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-17 05:19:41.806943
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_social', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('social_media', 'video', 'messaging', 'browser', 'games', 'productivity', 'education', 'news', 'essential', 'other')", name=op.f('ck_apps_category_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apps')),
    sa.UniqueConstraint('package_name', name=op.f('uq_apps_package_name'))
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('slug', 'chunk_index', name=op.f('uq_knowledge_documents_slug_chunk_index'))
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('risk', 'content', 'bandit', 'embedding', 'on_device')", name=op.f('ck_model_versions_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_name', 'version', name=op.f('uq_model_versions_model_name_version'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('run_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_decision', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.CheckConstraint("run_type IN ('evaluate', 'feedback', 'constitution', 'content_analysis', 'replay')", name=op.f('ck_agent_runs_run_type_valid')),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'degraded', 'failed')", name=op.f('ck_agent_runs_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_started', 'agent_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('entry_hash', name=op.f('uq_audit_logs_entry_hash')),
    sa.UniqueConstraint('seq', name=op.f('uq_audit_logs_seq'))
    )
    op.create_index('ix_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bandit_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('n_features', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_updates', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bandit_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_bandit_states'))
    )
    op.create_table('behavior_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feature_date', sa.Date(), nullable=False),
    sa.Column('total_social_seconds', sa.Integer(), nullable=False),
    sa.Column('total_screen_seconds', sa.Integer(), nullable=False),
    sa.Column('productive_seconds', sa.Integer(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('long_sessions_count', sa.Integer(), nullable=False),
    sa.Column('max_session_seconds', sa.Integer(), nullable=False),
    sa.Column('opens_count', sa.Integer(), nullable=False),
    sa.Column('focus_seconds', sa.Integer(), nullable=False),
    sa.Column('night_social_seconds', sa.Integer(), nullable=False),
    sa.Column('interventions_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('overridden_count', sa.Integer(), nullable=False),
    sa.Column('hourly_social_seconds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('app_seconds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_behavior_features_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behavior_features')),
    sa.UniqueConstraint('user_id', 'feature_date', name=op.f('uq_behavior_features_user_id_feature_date'))
    )
    op.create_index(op.f('ix_behavior_features_user_id'), 'behavior_features', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=48), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope IN ('usage_monitoring', 'content_text_analysis', 'cloud_ai_reasoning', 'screenshot_analysis', 'transcript_analysis', 'memory_personalization', 'anonymized_research')", name=op.f('ck_consents_scope_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('user_id', 'scope', name=op.f('uq_consents_user_id_scope'))
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("owner_type IN ('memory', 'knowledge')", name=op.f('ck_embeddings_owner_type_valid')),
    sa.CheckConstraint('dim > 0 AND dim <= 4096', name=op.f('ck_embeddings_dim_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_embeddings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('owner_type', 'owner_id', 'model', name=op.f('uq_embeddings_owner_type_owner_id_model'))
    )
    op.create_index('ix_embeddings_hnsw_384', 'embeddings', [sa.literal_column('(embedding::vector(384)) vector_cosine_ops')], unique=False, postgresql_using='hnsw', postgresql_where=sa.text('dim = 384'))
    op.create_index(op.f('ix_embeddings_user_id'), 'embeddings', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_temporary', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'archived')", name=op.f('ck_goals_status_valid')),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('ck_goals_priority_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("memory_type IN ('semantic', 'episodic', 'preference', 'insight')", name=op.f('ck_memories_memory_type_valid')),
    sa.CheckConstraint("source IN ('user', 'system', 'learning')", name=op.f('ck_memories_source_valid')),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name=op.f('ck_memories_importance_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index('ix_memories_user_type', 'memories', ['user_id', 'memory_type'], unique=False)
    op.create_table('policy_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('app_package', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=280), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('allow_once', 'pause', 'disable_30m', 'disable_until_tomorrow', 'emergency')", name=op.f('ck_policy_overrides_kind_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_policy_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_overrides'))
    )
    op.create_index(op.f('ix_policy_overrides_user_id'), 'policy_overrides', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('app_package', sa.String(length=255), nullable=False),
    sa.Column('app_category', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('scroll_events', sa.Integer(), nullable=False),
    sa.Column('focus_mode', sa.Boolean(), nullable=False),
    sa.Column('content_category', sa.String(length=32), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.CheckConstraint("app_category IN ('social_media', 'video', 'messaging', 'browser', 'games', 'productivity', 'education', 'news', 'essential', 'other')", name=op.f('ck_sessions_app_category_valid')),
    sa.CheckConstraint("content_category IN ('education', 'career', 'technology', 'news', 'entertainment', 'advertising', 'gaming', 'sports', 'short_form_video', 'clickbait', 'social', 'productivity', 'communication', 'unknown')", name=op.f('ck_sessions_content_category_valid')),
    sa.CheckConstraint('duration_seconds >= 0', name=op.f('ck_sessions_duration_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('ix_sessions_user_started', 'sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('intervention_style', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('guardian_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('content_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_social_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('device_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("intervention_style IN ('gentle', 'balanced', 'strict')", name=op.f('ck_user_preferences_intervention_style_valid')),
    sa.CheckConstraint("theme IN ('system', 'light', 'dark')", name=op.f('ck_user_preferences_theme_valid')),
    sa.CheckConstraint('daily_social_limit_minutes IS NULL OR (daily_social_limit_minutes >= 5 AND daily_social_limit_minutes <= 1440)', name=op.f('ck_user_preferences_daily_limit_range')),
    sa.CheckConstraint('retention_days >= 1 AND retention_days <= 3650', name=op.f('ck_user_preferences_retention_days_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    op.create_table('agent_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('ok', 'skipped', 'error', 'fallback')", name=op.f('ck_agent_steps_status_valid')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps')),
    sa.UniqueConstraint('run_id', 'seq', name=op.f('uq_agent_steps_run_id_seq'))
    )
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('app_package', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("event_type IN ('APP_OPENED', 'APP_CLOSED', 'SESSION_STARTED', 'SESSION_EXTENDED', 'FOCUS_STARTED', 'FOCUS_ENDED', 'RISK_DETECTED', 'INTERVENTION_TRIGGERED', 'INTERVENTION_ACCEPTED', 'INTERVENTION_OVERRIDDEN', 'GOAL_UPDATED', 'POLICY_UPDATED', 'GUARDIAN_PAUSED', 'GUARDIAN_RESUMED', 'EMERGENCY_OVERRIDE', 'CONSENT_CHANGED', 'USAGE_SUMMARY', 'DATA_DELETED')", name=op.f('ck_events_event_type_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_events_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('user_id', 'client_event_id', name=op.f('uq_events_user_id_client_event_id'))
    )
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index('ix_events_user_occurred', 'events', ['user_id', 'occurred_at'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('app_package', sa.String(length=255), nullable=True),
    sa.Column('proposed_decision', sa.String(length=32), nullable=False),
    sa.Column('final_decision', sa.String(length=32), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guardrail_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bandit_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('command', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("decided_by IN ('deterministic', 'bandit', 'llm', 'fallback', 'override')", name=op.f('ck_interventions_decided_by_valid')),
    sa.CheckConstraint("final_decision IN ('ALLOW', 'SOFT_WARNING', 'MINDFUL_PROMPT', 'DELAY', 'LIMITED_ACCESS', 'TEMPORARY_BLOCK', 'FOCUS_MODE', 'REQUEST_CONFIRMATION')", name=op.f('ck_interventions_final_decision_valid')),
    sa.CheckConstraint("proposed_decision IN ('ALLOW', 'SOFT_WARNING', 'MINDFUL_PROMPT', 'DELAY', 'LIMITED_ACCESS', 'TEMPORARY_BLOCK', 'FOCUS_MODE', 'REQUEST_CONFIRMATION')", name=op.f('ck_interventions_proposed_decision_valid')),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'accepted', 'overridden', 'ignored', 'expired', 'revoked')", name=op.f('ck_interventions_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_interventions_confidence_range')),
    sa.CheckConstraint('duration_minutes >= 0 AND duration_minutes <= 120', name=op.f('ck_interventions_duration_range')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_interventions_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_interventions_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interventions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    op.create_index('ix_interventions_user_created', 'interventions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_interventions_user_id'), 'interventions', ['user_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'error', 'invalid_output', 'budget_exceeded', 'timeout', 'cached')", name=op.f('ck_llm_calls_status_valid')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_llm_calls_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_calls_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index('ix_llm_calls_created', 'llm_calls', ['created_at'], unique=False)
    op.create_index('ix_llm_calls_user_created', 'llm_calls', ['user_id', 'created_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled', 'archived')", name=op.f('ck_policies_status_valid')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_policies_goal_id_goals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_policies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index(op.f('ix_policies_user_id'), 'policies', ['user_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('distraction_risk', sa.Float(), nullable=False),
    sa.Column('doomscroll_probability', sa.Float(), nullable=False),
    sa.Column('goal_conflict', sa.Float(), nullable=False),
    sa.Column('intervention_urgency', sa.Float(), nullable=False),
    sa.Column('continuation_probability', sa.Float(), nullable=False),
    sa.Column('predicted_productivity_loss_minutes', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('rules', 'ml', 'hybrid')", name=op.f('ck_risk_scores_method_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_risk_scores_confidence_range')),
    sa.CheckConstraint('continuation_probability >= 0 AND continuation_probability <= 1', name=op.f('ck_risk_scores_continuation_probability_range')),
    sa.CheckConstraint('distraction_risk >= 0 AND distraction_risk <= 1', name=op.f('ck_risk_scores_distraction_risk_range')),
    sa.CheckConstraint('doomscroll_probability >= 0 AND doomscroll_probability <= 1', name=op.f('ck_risk_scores_doomscroll_probability_range')),
    sa.CheckConstraint('goal_conflict >= 0 AND goal_conflict <= 1', name=op.f('ck_risk_scores_goal_conflict_range')),
    sa.CheckConstraint('intervention_urgency >= 0 AND intervention_urgency <= 1', name=op.f('ck_risk_scores_intervention_urgency_range')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_risk_scores_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_risk_scores_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index('ix_risk_scores_user_created', 'risk_scores', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_user_id'), 'risk_scores', ['user_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'invalid_input', 'invalid_output', 'denied', 'error')", name=op.f('ck_tool_calls_status_valid')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_tool_calls_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tool_calls_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index(op.f('ix_tool_calls_run_id'), 'tool_calls', ['run_id'], unique=False)
    op.create_table('content_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('goal_relevance', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classifier', sa.String(length=64), nullable=False),
    sa.Column('injection_detected', sa.Boolean(), nullable=False),
    sa.Column('injection_score', sa.Float(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('education', 'career', 'technology', 'news', 'entertainment', 'advertising', 'gaming', 'sports', 'short_form_video', 'clickbait', 'social', 'productivity', 'communication', 'unknown')", name=op.f('ck_content_signals_category_valid')),
    sa.CheckConstraint("goal_relevance IN ('goal_relevant', 'goal_irrelevant', 'neutral')", name=op.f('ck_content_signals_goal_relevance_valid')),
    sa.CheckConstraint("source IN ('metadata', 'text', 'screenshot', 'transcript')", name=op.f('ck_content_signals_source_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_content_signals_confidence_range')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_content_signals_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_content_signals_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_content_signals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_signals'))
    )
    op.create_index(op.f('ix_content_signals_user_id'), 'content_signals', ['user_id'], unique=False)
    op.create_table('intervention_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intervention_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('accepted', 'overridden', 'ignored', 'stopped_session', 'continued_session', 'returned_to_task', 'disabled_protection')", name=op.f('ck_intervention_outcomes_outcome_valid')),
    sa.CheckConstraint('reward >= -1 AND reward <= 1', name=op.f('ck_intervention_outcomes_reward_range')),
    sa.CheckConstraint('satisfaction IS NULL OR (satisfaction >= 1 AND satisfaction <= 5)', name=op.f('ck_intervention_outcomes_satisfaction_range')),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], name=op.f('fk_intervention_outcomes_intervention_id_interventions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_intervention_outcomes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intervention_outcomes')),
    sa.UniqueConstraint('intervention_id', name=op.f('uq_intervention_outcomes_intervention_id'))
    )
    op.create_index(op.f('ix_intervention_outcomes_user_id'), 'intervention_outcomes', ['user_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('compiled_by', sa.String(length=16), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("compiled_by IN ('deterministic', 'llm', 'manual')", name=op.f('ck_policy_versions_compiled_by_valid')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_versions_policy_id_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_policy_versions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('policy_id', 'version', name=op.f('uq_policy_versions_policy_id_version'))
    )
    op.create_index(op.f('ix_policy_versions_user_id'), 'policy_versions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_versions_user_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_intervention_outcomes_user_id'), table_name='intervention_outcomes')
    op.drop_table('intervention_outcomes')
    op.drop_index(op.f('ix_content_signals_user_id'), table_name='content_signals')
    op.drop_table('content_signals')
    op.drop_index(op.f('ix_tool_calls_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_risk_scores_user_id'), table_name='risk_scores')
    op.drop_index('ix_risk_scores_user_created', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_policies_user_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_llm_calls_user_created', table_name='llm_calls')
    op.drop_index('ix_llm_calls_created', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_interventions_user_id'), table_name='interventions')
    op.drop_index('ix_interventions_user_created', table_name='interventions')
    op.drop_table('interventions')
    op.drop_index('ix_events_user_occurred', table_name='events')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_table('user_preferences')
    op.drop_index('ix_sessions_user_started', table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_policy_overrides_user_id'), table_name='policy_overrides')
    op.drop_table('policy_overrides')
    op.drop_index('ix_memories_user_type', table_name='memories')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_embeddings_user_id'), table_name='embeddings')
    op.drop_index('ix_embeddings_hnsw_384', table_name='embeddings', postgresql_using='hnsw', postgresql_where=sa.text('dim = 384'))
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_behavior_features_user_id'), table_name='behavior_features')
    op.drop_table('behavior_features')
    op.drop_table('bandit_states')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_started', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('users')
    op.drop_table('model_versions')
    op.drop_table('knowledge_documents')
    op.drop_table('apps')
    # ### end Alembic commands ###
